kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-elastic-master
  namespace: ns-elastic
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/data/es/master"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-elastic-master
  namespace: ns-elastic
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ns-elastic
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  serviceName: elasticsearch-master
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      role: master
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      volumes:
       - name: pv-storage-elastic-master
         persistentVolumeClaim:
           claimName: pv-claim-elastic-master
      containers:
        - name: elasticsearch
          image: dockerhub-pr.yeshj.com/ops/elasticsearch:7.2.0
          resources:
            requests:
              memory: 2Gi
              cpu: 1.0
            limits:
              memory: 4Gi
              cpu: 2.0
          command: ["bash", "-c", "ulimit -l unlimited && sysctl -w vm.max_map_count=262144 && chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data && exec su elasticsearch docker-entrypoint.sh"]
          ports:
            - containerPort: 19200
              name: http
            - containerPort: 19300
              name: transport
          env:
            - name: discovery.seed_hosts
              value: "elasticsearch-master.ns-elastic.svc.cluster.local"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m

            - name: node.master
              value: "true"
            - name: node.ingest
              value: "false"
            - name: node.data
              value: "false"

            - name: cluster.name
              value: "elasticsearch-cluster-v7"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
           - mountPath: /usr/share/elasticsearch/data
             name: pv-storage-elastic-master

          # Gave permission to init container
          securityContext:
            privileged: true

      # Pull image from private repo
      imagePullSecrets:
      - name: regcred-elastic
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: ns-elastic
  name: elasticsearch-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: master
