---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gohangout-config
  namespace: ns-elastic
data:
  gohangout-config-dnsmasq-k8s: |
    inputs:
        #- Stdin:
        #    codec: json
        - Kafka:
            topic:
                dnsmasq: 1
            #assign:
            #    healer.test: [0]
            codec: json
            consumer_settings:
                bootstrap.servers: "192.168.38.93:9092"
                group.id: gohangout-dnsmasq-qa-k8s-topic
                max.partition.fetch.bytes: 10485760
                auto.commit.interval.ms: 5000
                from.beginning: false
    
    filters:
        - Grok:
            src: message
            match:
                - '^(?P<logtime>\S+ \S+ \S+) (?P<pname>\w+)\[(?P<pid>\d+)\]: (?P<action>\S+) (?P<rawdata>.*)$'
                - '^(?P<logtime>\S+  \S+ \S+) (?P<pname>\w+)\[(?P<pid>\d+)\]: (?P<action>\S+) (?P<rawdata>.*)$'
            remove_fields: ['message']
        - Date:
            src: 'logtime'
            location: Asia/Shanghai
            add_year: true
            formats:
                - '2006Jan 2 15:04:05'
            remove_fields: ["logtime"]
    
    outputs:
        #- Stdout: {}
        - Elasticsearch:
            hosts:
                - http://192.168.36.145:39200
            index: 'gohangout-kafka-dnsmasq-%{+2006-01-02}'
            index_type: "logs"
            bulk_actions: 5000
            bulk_size: 20
            flush_interval: 30
            concurrent: 1
            compress: false
            retry_response_code: [401, 502]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gohangout-k8s-dnsmasq
  namespace: ns-elastic
  labels:
    app: gohangout-k8s-dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gohangout-k8s-dnsmasq
  template:
    metadata:
      labels:
        app: gohangout-k8s-dnsmasq
    spec:
      containers:
      - name: gohangout-k8s-dnsmasq
        image: dockerhub-pr.yeshj.com/ops/gohangout:1.2.7-3
        command: ["/bin/sh","-c"]
        args: ["/opt/gohangout/gohangout --config /usr/share/gohangout/indexer-kafka-dnsmasq-k8s.yml -logtostderr -v 5 --worker 3"]
        volumeMounts:
        - name: vm-config
          mountPath: /usr/share/gohangout
      imagePullSecrets:
      - name: regcred-elastic
      volumes:
      - name: vm-config
        configMap:
          name: gohangout-config
          items:
          - key: gohangout-config-dnsmasq-k8s
            path: indexer-kafka-dnsmasq-k8s.yml
